admin_andijon/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('api/', include('api.urls'))
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

api/urls.py
from django.urls import path
from .views import *


urlpatterns = [
    path("club/", Clubs),
    path("new/", New),
    path("single_new/<int:pk>/", Singlenews),
    path("academy/", Academy),
    path("game_view/", game_view),
    path("game_chart/", game_chart),
    path("media/", Media),
    path("single_media/<int:pk>/", Singlevideo),
    path("register/", Register),
    path("login/", login),
    path("shop/", Shop),
    path('singe_shop/<int:pk>/', Singleshop),
    path('wishlist_add/<int:pk>/', WishlistAdd),
    path('order_item_create/<int:pk>/', OrderItemCreate),
    path('order_create/', OrderCreate),
]

main/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    status = models.IntegerField(
        choices=(
            (1, 'admin'),
            (2, 'user')
        ), default=2)
    country = models.CharField(max_length=210)
    number = models.IntegerField(null=True, blank=True)


class Staff(models.Model):
    status = {
        (1, 'trainer'),
        (2, 'sub-trainer'),
        (3, 'main-analytic'),
        (4, 'doctor'),
        (5, 'goalkeeper-trainer'),
        (6, 'admin')
    }
    role = models.IntegerField(choices=status)
    name = models.CharField(max_length=210)
    sur_name = models.CharField(max_length=210)
    birth = models.DateField()
    image = models.ImageField(upload_to='staff/')


class Players(models.Model):
    first_name = models.CharField(max_length=225)
    last_name = models.CharField(max_length=225)
    number = models.IntegerField(unique=True)
    TYPES = {
        (1, 'forward'),
        (2, 'midfielder'),
        (3, 'defender'),
        (4, 'goalkeeper'),
    }
    position = models.IntegerField(default=1, choices=TYPES)
    birth = models.DateField()
    image = models.ImageField(upload_to='player/')
    captain = models.BooleanField(default=False, null=True, blank=True)
    sub_captain = models.BooleanField(default=False)


class Passes(models.Model):
    all = models.IntegerField()
    successful = models.IntegerField()
    percent = models.IntegerField()
    status = models.IntegerField(choices=(
        (1, 'passes'),
        (2, 'long-passes'),
        (3, 'helps'),
        (4, 'crosses')
    ))


class StadiumImage(models.Model):
    img = models.ImageField(upload_to='stadium/')


class Stadium(models.Model):
    name = models.CharField(max_length=210)
    capacity = models.IntegerField()
    image = models.ManyToManyField(StadiumImage)


class Fc(models.Model):
    status = models.IntegerField(choices=((1, 'Fc'), (2, 'Club')))
    players = models.ManyToManyField(Players, null=True, blank=True)
    staff = models.ManyToManyField(Staff, null=True, blank=True)
    name = models.CharField(max_length=210)
    trainer = models.CharField(max_length=210, null=True, blank=True)
    logo = models.ImageField(upload_to='fc/')
    stadium = models.ForeignKey(Stadium, on_delete=models.CASCADE, null=True, blank=True)


class Advertiser(models.Model):
    logo = models.ImageField(upload_to='advertiser/')
    url = models.URLField()


class News(models.Model):
    image = models.ImageField(upload_to='news/')
    title = models.CharField(max_length=255)
    text = models.TextField()
    date = models.DateTimeField()


class Videos(models.Model):
    video = models.FileField(upload_to='video/')
    description = models.TextField()
    date = models.DateTimeField(auto_now=True)
    is_top = models.BooleanField(default=False)


class Info(models.Model):
    insta = models.URLField()
    telegram = models.URLField()
    twitter = models.URLField()
    youtube = models.URLField()
    facebook = models.URLField()
    phone = models.IntegerField()
    email = models.EmailField()
    bio = models.TextField()
    logo = models.ImageField(upload_to='info/')


class About(models.Model):
    image = models.ImageField(null=True, blank=True, upload_to='academy/')
    text = models.TextField()
    title = models.TextField()


class Preview(models.Model):
    guest = models.ForeignKey(Fc, on_delete=models.CASCADE, related_name='guest')
    host = models.ForeignKey(Fc, on_delete=models.CASCADE, related_name='host')
    date = models.DateTimeField()
    match_day = models.CharField(max_length=255)


class Squad(models.Model):
    team = models.ManyToManyField(Players)
    game = models.ForeignKey(Preview, on_delete=models.CASCADE)


class Line(models.Model):
    team = models.ManyToManyField(Players)
    squad_list = models.ForeignKey(Squad, on_delete=models.CASCADE)


class Substitute(models.Model):
    squad = models.ForeignKey(Squad, on_delete=models.CASCADE, related_name='player_out')
    line = models.ForeignKey(Line, on_delete=models.CASCADE, related_name='player_on')
    minute = models.IntegerField()


class Action(models.Model):
    which = models.ForeignKey(Fc, on_delete=models.CASCADE)
    who = models.ForeignKey(Players, on_delete=models.CASCADE, null=True, blank=True)
    club_who = models.CharField(max_length=215)
    action = models.IntegerField(choices=((1, 'yellow-card'), (2, 'red-card'), (3, 'goal')))
    minute = models.IntegerField()


class Game(models.Model):
    line = models.ForeignKey(Line, on_delete=models.CASCADE, related_name='line')
    guest_action = models.ManyToManyField(Action, related_name='guest')
    host_action = models.ManyToManyField(Action, related_name='host')
    possession = models.FloatField()
    passes = models.ManyToManyField(Passes)
    subs = models.ManyToManyField(Substitute, null=True, blank=True)
    mvp = models.ForeignKey(Line, on_delete=models.CASCADE, related_name='mvp')


class Size(models.Model):
    size = models.IntegerField(choices=(
        (1, 'S'),
        (2, 'M'),
        (3, 'L'),
        (4, 'XL'),
        (5, 'XXL'),
        (6, '3XL'),
    ))
    available = models.BooleanField(default=True)


class Images(models.Model):
    image = models.ImageField(upload_to='media/')


class Product(models.Model):
    name = models.CharField(max_length=210)
    image = models.ManyToManyField(Images)
    bonus = models.IntegerField(null=True, blank=True)
    price = models.DecimalField(max_digits=100, decimal_places=2)
    text = models.TextField()
    size = models.ManyToManyField(Size)
    rating = models.IntegerField(choices=(
        (0, 'no rating'),
        (1, '1 star'),
        (2, '2 star'),
        (3, '3 star'),
        (4, '4 star'),
        (5, '5 star'),
    ), default=0)


class Wishlist(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)


class OrderItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField()


class Region(models.Model):
    name = models.CharField(max_length=210)


class Order(models.Model):
    order_item = models.ManyToManyField(OrderItem)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    surname = models.CharField(max_length=255)
    phone_number = models.CharField(max_length=255)
    address = models.CharField(max_length=255)
    postal_code = models.CharField(max_length=255)
    email = models.EmailField()
    region = models.ForeignKey(Region, on_delete=models.CASCADE)
    city = models.CharField(max_length=210)
    status = models.IntegerField(choices=(
        (0, 'accepted'),
        (1, 'preparing'),
        (2, 'finished'),
    ), default=0)


class Chat(models.Model):
    chat_id = models.CharField(max_length=1000)


class Telegram(models.Model):
    bot_token = models.CharField(max_length=1000)
    chat_id = models.ManyToManyField(Chat)

templates/game.html
{% extends 'base.html' %}
{% block content %}

        <main class="content">
            <div class="container-fluid p-0">
                <form action="{% url 'game' %}" method="post" style="display:flex; justify-content: center" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-2 col-sm-6 col-xl mt-2 d-flex">
                            <input type="text" name="name" placeholder="Name" class="form-control" required>
                        </div>
                        <div class="col-2 col-sm-6 col-xl mt-2 d-flex">
                            <input type="text" name="trainer" placeholder="Trainer" class="form-control" required>
                        </div>
                        <div class="col-2 form-group mt-2">
                            <select class="form-control select2" name="line">
                                {% for i in line %}
                                    <option value="{{ i.id }}">{{ i.squad_list.team.first_name }}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <div class="col-2 form-group mt-2">
                            <select class="form-control select2" name="host">
                                {% for i in host %}
                                    <option value="{{ i.id }}">{{ i.action }}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <div class="col-2 form-group mt-2">
                            <select class="form-control select2" name="guest">
                                {% for i in guest %}
                                    <option value="{{ i.id }}">{{ i.action }}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <div class="col-2 form-group mt-2">
                            <select class="form-control select2" name="pass" multiple>
                                {% for i in passes %}
                                    <option value="{{ i.id }}">{{ i.get_status_display }}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <div class="col-2 form-group mt-2">
                            <select class="form-control select2" name="subs" multiple>
                                {% for i in subs %}
                                    <option value="{{ i.id }}">{{ i.subs.line.team.first_name }}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <div class="col-2 form-group mt-2">
                            <select class="form-control select2" name="mvp">
                                {% for i in line %}
                                    <option value="{{ i.id }}">{{ i.first_name }}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <div class="col-2 col-sm-6 col-xl mt-2 d-flex">
                            <input type="number" name="possession" placeholder="Possession" class="form-control" required>
                        </div>
                        <div class="col-2 col-sm-6 col-xl mt-2 d-flex">
                            <button type="submit" class="btn btn-primary">Save</button>
                        </div>
                    </div>
                </form>
            </div>
            <div class="row">
                <div class="col-12 col-xl-12">
                    <div class="card">
                        <table class="table" style="text-align: center;">
                            <thead>
                                <tr>
                                    <th>Line</th>
                                    <th>Preview</th>
                                    <th>Host</th>
                                    <th>Guest</th>
                                    <th>Possession</th>
                                    <th>Passes</th>
                                    <th>Substitute</th>
                                    <th>Mvp</th>
                                    <th>Update</th>
                                    <th>Delete</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for i in game %}
                                    <tr>
                                        <td>{{ i.line.team.first.first_name }}</td>
                                        <td>{{ i.line.squad_list.game.match_day }}</td>
                                        <td>{{ i.host.action }}</td>
                                        <td>{{ i.guest.action }}</td>
                                        <td>{{ i.possession }}</td>
                                        <td>{{ i.passes.passes }}</td>
                                        <td>{{ i.subs.minute }}</td>
                                        <td>{{ i.mvp.first_name }}</td>
                                        <td class="d-none d-md-table-cell"><a href="{% url 'update-game' i.id %}"><i class="align-middle" data-feather="edit-2"></i></a></td>
                                        <td><a href="{% url 'delete-game' i.id %}"><button type="submit" data-toggle="modal" data-target="#sizedModalMd" data-feather="trash">Delete</button></a></td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>

        </main>

{% endblock %}

templates/get-product-image.html
{% extends 'base.html' %}
{% block content %}

        <main class="main-content">
            <div class="row">
                <div class="col-12 col-xl-12">
                    <div class="card">
                        <table class="table" style="text-align: center;">
                            <thead>
                                <tr>
                                    <th>Image</th>
                                    <th>Update</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for i in image %}
                                    <tr>
                                        <td><img src="{{ i.image.url }}" class="rounded-circle" style="width: 50px; height: 50px"></td>
                                        <td class="d-none d-md-table-cell"><a href="{% url 'update-image' i.id %}"><i class="align-middle" data-feather="edit-2"></i></a></td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </main>

{% endblock %}

templates/get-staff.html
{% extends 'base.html' %}
{% block content %}

        <main class="main-content">
            <div class="card-body">
                <table class="table table-bordered" style="text-align:center">
                    <thead>
                        <tr>
                            <th scope="col">Role</th>
                            <th scope="col">Name</th>
                            <th scope="col">Last-Name</th>
                            <th scope="col">Image</th>
                            <th scope="col">Birth-Date</th>
                            <th scope="col">Change</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for i in staff %}
                            <tr>
                                <td>{{ i.get_role_display }}</td>
                                <td>{{ i.name }}</td>
                                <td>{{ i.sur_name }}</td>
                                <td><img src="{{ i.image.url }}"></td>
                                <td>{{ i.birth }}</td>
                                <td class="d-none d-md-table-cell"><a href="{% url 'update-staff' i.id %}"><i class="align-middle" data-feather="edit-2"></i></a></td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </main>

{% endblock %}

templates/info.html
{% extends 'base.html' %}
{% block content %}

        <main class="main-content">
            <div class="container-fluid p-0">
                <div class="card">
                    <div class="card-body">
                        <form action="{% url 'add-info' %}" method="post" style="margin-bottom: 20px; display:flex; justify-content: center" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-2 col-sm-6 col-xl mt-2 d-flex">
                                    <input type="text" name="insta" placeholder="Instagram" class="form-control" required>
                                </div>
                                <div class="col-2 col-sm-6 col-xl mt-2 d-flex">
                                    <input type="text" name="telegram" placeholder="Telegram" class="form-control" required>
                                </div>
                                <div class="col-2 col-sm-6 col-xl mt-2 d-flex">
                                    <input type="text" name="twitter" placeholder="Twitter" class="form-control" required>
                                </div>
                                <div class="col-2 col-sm-6 col-xl mt-2 d-flex">
                                    <input type="text" name="youtube" placeholder="Youtube" class="form-control" required>
                                </div>
                                <div class="col-2 col-sm-6 col-xl mt-2 d-flex">
                                    <input type="text" name="facebook" placeholder="Facebook" class="form-control" required>
                                </div>
                                <div class="col-2 col-sm-6 col-xl mt-2 d-flex">
                                    <input type="number" name="phone" placeholder="Phone" class="form-control" required>
                                </div>
                                <div class="col-2 col-sm-6 col-xl mt-2 d-flex">
                                    <input type="email" name="email" placeholder="email" class="form-control" required>
                                </div>
                                <div class="col-2 col-sm-6 col-xl mt-2 d-flex">
                                    <input type="text" name="bio" placeholder="bio" class="form-control" required>
                                </div>
                                <div class="custom-file col-2 mt-2" style="margin-bottom: 5px; margin-top: -3px;">
                                    <label class="custom-file-label" for="customFile"><span style="margin-right: 98px">Choose file</span></label>
                                    <input type="file" style="padding:20px 0;width:195px;right: 16px;" class="custom-file-input form-control" name="logo" id="customFile" required>
                                </div>
                                <div class="col-2 col-sm-5 col-xl mt-2 d-flex">
                                    <button type="submit" style="height: 43px; width:70px" class="btn btn-primary">Save</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-12 col-xl-12">
                    <div class="card">
                        <table class="table" style="text-align: center;">
                            <thead>
                                <tr>
                                    <th>Instagram</th>
                                    <th>Telegram</th>
                                    <th>Twitter</th>
                                    <th>Youtube</th>
                                    <th>Facebook</th>
                                    <th>Phone</th>
                                    <th>Email</th>
                                    <th>Logo</th>
                                    <th>Update</th>
                                    <th>Delete</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for i in info %}
                                    <tr>
                                        <td>{{ i.insta }}</td>
                                        <td>{{ i.telegram }}</td>
                                        <td>{{ i.twitter }}</td>
                                        <td>{{ i.youtube }}</td>
                                        <td>{{ i.facebook }}</td>
                                        <td>{{ i.phone }}</td>
                                        <td>{{ i.email }}</td>
                                        <td><img src="{{ i.logo.url }}" class="rounded-circle" style="width: 50px; height: 50px"></td>
                                        <td class="d-none d-md-table-cell"><a href="{% url 'update-info' i.id %}"><i class="align-middle" data-feather="edit-2"></i></a></td>
                                        <td>
	    									<a href="{% url 'delete-info' i.id %}"><button type="submit" data-toggle="modal" data-target="#sizedModalMd" data-feather="trash">Delete</button></a>
										</td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>

        </main>

{% endblock %}

templates/page-404.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no" name="viewport">
    <title>Andijon-FC Dashboard</title>
    <link rel="stylesheet" href="{% static 'assets/css/app.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/components.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/custom.css' %}">
    <link rel='shortcut icon' type='image/x-icon' href='{% static "assets/img/favicon.ico" %}' />
</head>
<body>
    <div id="app">
        <section class="section">
            <div class="container mt-5">
                <div class="page-error">
                    <div class="page-inner">
                        <h1>404</h1>
                        <div class="page-description">
                            The page you were looking for could not be found.
                        </div>
                        <div class="page-search">
                            <div class="new-input">
                                {% if user.is_authenticated %}
                                    <a href="{% url 'dashboard' %}"><button class="btn btn-primary btn-lg">Back to Dashboard</button></a>
                                {% else %}
                                    <a href="{% url 'sign-in' %}"><button class="btn btn-primary btn-lg">Back to Login</button></a>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
    <script src="{% static 'assets/js/app.min.js' %}"></script>
    <script src="{% static 'assets/js/scripts.js' %}"></script>
    <script src="{% static 'assets/js/custom.js' %}"></script>
</body>
</html>

templates/passes.html
{% extends 'base.html' %}
{% block content %}

        <main class="main-content">
            <div class="container-fluid p-0">
                <div class="card">
                    <div class="card-body">
                        <form action="{% url 'add-passes' %}" method="post" style="margin-bottom: 20px; display:flex; justify-content: center" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-2 col-sm-6 col-xl mt-2 d-flex">
                                    <input type="number" name="passes" placeholder="All-Passes" class="form-control" required>
                                </div>
                                <div class="col-2 col-sm-6 col-xl mt-2 d-flex">
                                    <input type="number" name="successful" placeholder="Success-Passes" class="form-control" required>
                                </div>
                                <div class="col-3 input-group mt-2 mr-sm-2">
                                    <select name="status" class="form-control select2">
                                        <option value="1">Passes</option>
                                        <option value="2">Long-Passes</option>
                                        <option value="3">Helps</option>
                                        <option value="4">Crosses</option>
                                    </select>
                                </div>
                                <div class="col-2 col-sm-6 col-xl mt-2 d-flex">
                                    <button type="submit" class="btn btn-primary">Save</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-12 col-xl-12">
                    <div class="card">
                        <table class="table" style="text-align: center;">
                            <thead>
                                <tr>
                                    <th>All</th>
                                    <th>Successful</th>
                                    <th>Successful-Percent</th>
                                    <th>Passes</th>
                                    <th>Update</th>
                                    <th>Delete</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for i in passes %}
                                    <tr>
                                        <td>{{ i.all }}</td>
                                        <td>{{ i.successful }}</td>
                                        <td>{{ i.percent }}%</td>
                                        <td>{{ i.get_status_display }}</td>
                                        <td class="d-none d-md-table-cell"><a href="{% url 'update-passes' i.id %}"><i class="align-middle" data-feather="edit-2"></i></a></td>
                                        <td>
    										<a href="{% url 'delete-passes' i.id %}"><button type="submit" data-toggle="modal" data-target="#sizedModalMd" data-feather="trash">Delete</button></a>
										</td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>

        </main>

{% endblock %}

templates/staff.html
{% extends 'base.html' %}
{% block content %}
    <main class="main-content">
        <div class="card">
            <div class="card-header">
                <h4>Add Staff</h4>
            </div>
            <div class="card-body">
                <form class="form-inline" style="align-items: center;" action="{% url 'add-staff' %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-group col-2 mt-2">
                        <select name="role" class="form-control select2">
                            <option value="1">trainer</option>
                            <option value="2">sub-trainer</option>
                            <option value="3">physiotherapist</option>
                            <option value="4">doctor</option>
                            <option value="5">goalkeeper-trainer</option>
                            <option value="6">admin</option>
                        </select>
                    </div>
                    <input type="text" class="col-2 mt-2 form-control" name="name" placeholder="Name" required>
                    <div class="col-2 input-group mr-sm-2 mt-2">
                        <input type="text" class="form-control" name="sur-name" placeholder="Sur-Name" required>
                    </div>
                    <div class="custom-file col-2 mt-2">
                        <label class="custom-file-label" for="customFile"><span style="margin-right: 93px">Choose file</span></label>
                        <input type="file" style="padding: 20px 0px 20px 0px;right: 16px;width: 195px;" class="custom-file-input form-control" name="image" id="customFile" required>
                    </div>
                    <div class="form-group col-2 mt-2">
                        <input type="text" name="date" class="form-control datepicker">
                    </div>
                    <button class="btn btn-primary mt-2" style="margin-left:30px" type="submit">Submit</button>
                </form>
            </div>
        </div>
        <div class="card">
            <div class="card-header">
                <h4>Staff</h4>
            </div>
            <div class="card-body">
                <table class="table table-bordered" style="text-align:center">
                    <thead>
                        <tr>
                            <th scope="col">Role</th>
                            <th scope="col">Name</th>
                            <th scope="col">Last-Name</th>
                            <th scope="col">Image</th>
                            <th scope="col">Birth-Date</th>
                            <th scope="col">Change</th>
                            <th scope="col">Delete</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for i in staff %}
                            <tr>
                                <td>{{ i.get_role_display }}</td>
                                <td>{{ i.name }}</td>
                                <td>{{ i.sur_name }}</td>
                                <td><img src="{{ i.image.url }}" style="width: 50px; height:50px"></td>
                                <td>{{ i.birth }}</td>
                                <td class="d-none d-md-table-cell"><a href="{% url 'update-staff' i.id %}"><i class="align-middle" data-feather="edit-2"></i></a></td>
                                <td class="table-action"><a href="{% url 'delete-staff' i.id %}"><i class="align-middle" data-feather="trash"></i></a></td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </main>
{% endblock %}